FROM node:22-slim

WORKDIR /app/src/viz

COPY src/viz/package.json src/viz/package-lock.json* ./
RUN npm install

COPY src/viz ./
COPY configs /app/configs

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
